;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-arb_compressed_texture_pixel_storage-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_compressed_texture_pixel_storage-system) 
(defsystem cl-glfw-opengl-arb_compressed_texture_pixel_storage :description "cl-glfw's arb_compressed_texture_pixel_storage binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-arb_compressed_texture_pixel_storage"))) 
