;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-nv_deep_texture3d-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_deep_texture3d-system) 
(defsystem cl-glfw-opengl-nv_deep_texture3d :description
 "cl-glfw's nv_deep_texture3d binding" :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-nv_deep_texture3d"))) 
