;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sgix_framezoom-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_framezoom-system) 
(defsystem cl-glfw-opengl-sgix_framezoom :description "cl-glfw's sgix_framezoom binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-sgix_framezoom"))) 
