;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-intel_parallel_arrays-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-intel_parallel_arrays-system) 
(defsystem cl-glfw-opengl-intel_parallel_arrays :description "cl-glfw's intel_parallel_arrays binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-intel_parallel_arrays"))) 
