;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-arb_texture_storage_multisample-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_texture_storage_multisample-system) 
(defsystem cl-glfw-opengl-arb_texture_storage_multisample
 :description "cl-glfw's arb_texture_storage_multisample binding"
 :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-arb_texture_storage_multisample"))) 
