;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-version_4_3-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-version_4_3-system) 
(defsystem cl-glfw-opengl-version_4_3 :description "cl-glfw's version_4_3 binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-version_4_3"))) 
