;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sun_triangle_list-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sun_triangle_list-system) 
(defsystem cl-glfw-opengl-sun_triangle_list :description
 "cl-glfw's sun_triangle_list binding" :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-sun_triangle_list"))) 
