;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-amd_sparse_texture-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-amd_sparse_texture-system) 
(defsystem cl-glfw-opengl-amd_sparse_texture :description "cl-glfw's amd_sparse_texture binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-amd_sparse_texture"))) 
