;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-img_texture_compression_pvrtc2-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-img_texture_compression_pvrtc2-system) 
(defsystem cl-glfw-opengl-img_texture_compression_pvrtc2 :description "cl-glfw's img_texture_compression_pvrtc2 binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-img_texture_compression_pvrtc2"))) 
