;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-nv_evaluators-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_evaluators-system) 
(defsystem cl-glfw-opengl-nv_evaluators :description "cl-glfw's nv_evaluators binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-nv_evaluators"))) 
