;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-oml_interlace-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-oml_interlace-system) 
(defsystem cl-glfw-opengl-oml_interlace :description "cl-glfw's oml_interlace binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-oml_interlace"))) 
