;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-nv_vertex_buffer_unified_memory-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_vertex_buffer_unified_memory-system) 
(defsystem cl-glfw-opengl-nv_vertex_buffer_unified_memory
 :description "cl-glfw's nv_vertex_buffer_unified_memory binding"
 :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-nv_vertex_buffer_unified_memory"))) 
