;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-oes_byte_coordinates-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-oes_byte_coordinates-system) 
(defsystem cl-glfw-opengl-oes_byte_coordinates :description
 "cl-glfw's oes_byte_coordinates binding" :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-oes_byte_coordinates"))) 
