;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-gl_khr_texture_compression_astc_ldr-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-gl_khr_texture_compression_astc_ldr-system) 
(defsystem cl-glfw-opengl-gl_khr_texture_compression_astc_ldr :description "cl-glfw's gl_khr_texture_compression_astc_ldr binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-gl_khr_texture_compression_astc_ldr"))) 
