;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-ati_texture_env_combine3-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_texture_env_combine3-system) 
(defsystem cl-glfw-opengl-ati_texture_env_combine3 :description "cl-glfw's ati_texture_env_combine3 binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-ati_texture_env_combine3"))) 
