;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-amd_vertex_shader_tessellator-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-amd_vertex_shader_tessellator-system) 
(defsystem cl-glfw-opengl-amd_vertex_shader_tessellator :description
 "cl-glfw's amd_vertex_shader_tessellator binding" :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-amd_vertex_shader_tessellator"))) 
