;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-ibm_static_data-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ibm_static_data-system) 
(defsystem cl-glfw-opengl-ibm_static_data :description
 "cl-glfw's ibm_static_data binding" :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-ibm_static_data"))) 
