;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-oes_fixed_point-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-oes_fixed_point-system) 
(defsystem cl-glfw-opengl-oes_fixed_point :description "cl-glfw's oes_fixed_point binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-oes_fixed_point"))) 
