;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-oes_single_precision-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-oes_single_precision-system) 
(defsystem cl-glfw-opengl-oes_single_precision :description "cl-glfw's oes_single_precision binding" :author "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp" :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components ((:file "opengl-oes_single_precision"))) 
