;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-khr_debug-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-khr_debug-system) 
(defsystem cl-glfw-opengl-khr_debug :description
 "cl-glfw's khr_debug binding" :author
 "Generated by cl-glfw's /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core)
 :components ((:file "opengl-khr_debug"))) 
