;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; amd_query_buffer_object

(defconstant +query-buffer-amd+ #x9192) 
(defconstant +query-buffer-binding-amd+ #x9193) 
(defconstant +query-result-no-wait-amd+ #x9194) 
(defconstant +query-buffer-amd+ #x9192) 
(defconstant +query-buffer-binding-amd+ #x9193) 
(defconstant +query-result-no-wait-amd+ #x9194) 
