;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_shadow_ambient

(defconstant +texture-compare-fail-value-arb+ #x80BF) 
(defconstant +texture-compare-fail-value-arb+ #x80BF) 
