;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; nv_compute_program5

(defconstant +compute-program-nv+ #x90FB) 
(defconstant +compute-program-parameter-buffer-nv+ #x90FC) 
(defconstant +compute-program-nv+ #x90FB) 
(defconstant +compute-program-parameter-buffer-nv+ #x90FC) 
