;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; amd_sparse_texture

(defconstant +virtual-page-size-x-amd+ #x9195) 
(defconstant +virtual-page-size-y-amd+ #x9196) 
(defconstant +virtual-page-size-z-amd+ #x9197) 
(defconstant +max-sparse-texture-size-amd+ #x9198) 
(defconstant +max-sparse-3d-texture-size-amd+ #x9199) 
(defconstant +max-sparse-array-texture-layers+ #x919A) 
(defconstant +min-sparse-level-amd+ #x919B) 
(defconstant +min-lod-warning-amd+ #x919C) 
(defconstant +texture-storage-sparse-bit-amd+ #x1) 
(defconstant +virtual-page-size-x-amd+ #x9195) 
(defconstant +virtual-page-size-y-amd+ #x9196) 
(defconstant +virtual-page-size-z-amd+ #x9197) 
(defconstant +max-sparse-texture-size-amd+ #x9198) 
(defconstant +max-sparse-3d-texture-size-amd+ #x9199) 
(defconstant +max-sparse-array-texture-layers+ #x919A) 
(defconstant +min-sparse-level-amd+ #x919B) 
(defconstant +min-lod-warning-amd+ #x919C) 
(defconstant +texture-storage-sparse-bit-amd+ #x1) 
(defglextfun "TextureStorageSparseAMD" texture-storage-sparse-amd
 :return "void" :args
 ((:name |texture| :type |UInt32| :direction :in)
  (:name |target| :type |GLenum| :direction :in)
  (:name |internalFormat| :type |GLenum| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in)
  (:name |depth| :type |SizeI| :direction :in)
  (:name |layers| :type |SizeI| :direction :in)
  (:name |flags| :type |GLbitfield| :direction :in))
 :category "AMD_sparse_texture" :deprecated nil :version "4.3") 
(defglextfun "TexStorageSparseAMD" tex-storage-sparse-amd :return
 "void" :args
 ((:name |target| :type |GLenum| :direction :in)
  (:name |internalFormat| :type |GLenum| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in)
  (:name |depth| :type |SizeI| :direction :in)
  (:name |layers| :type |SizeI| :direction :in)
  (:name |flags| :type |GLbitfield| :direction :in))
 :category "AMD_sparse_texture" :deprecated nil :version "4.3") 
(make-extension-loader |AMD_sparse_texture|
 (("TextureStorageSparseAMD" texture-storage-sparse-amd :return
   "void" :args
   ((:name |texture| :type |UInt32| :direction :in)
    (:name |target| :type |GLenum| :direction :in)
    (:name |internalFormat| :type |GLenum| :direction :in)
    (:name |width| :type |SizeI| :direction :in)
    (:name |height| :type |SizeI| :direction :in)
    (:name |depth| :type |SizeI| :direction :in)
    (:name |layers| :type |SizeI| :direction :in)
    (:name |flags| :type |GLbitfield| :direction :in))
   :category "AMD_sparse_texture" :deprecated nil :version "4.3")
  ("TexStorageSparseAMD" tex-storage-sparse-amd :return "void" :args
   ((:name |target| :type |GLenum| :direction :in)
    (:name |internalFormat| :type |GLenum| :direction :in)
    (:name |width| :type |SizeI| :direction :in)
    (:name |height| :type |SizeI| :direction :in)
    (:name |depth| :type |SizeI| :direction :in)
    (:name |layers| :type |SizeI| :direction :in)
    (:name |flags| :type |GLbitfield| :direction :in))
   :category "AMD_sparse_texture" :deprecated nil :version "4.3"))) 
