;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_compressed_texture_pixel_storage

(defconstant +unpack-compressed-block-width+ #x9127) 
(defconstant +unpack-compressed-block-height+ #x9128) 
(defconstant +unpack-compressed-block-depth+ #x9129) 
(defconstant +unpack-compressed-block-size+ #x912A) 
(defconstant +pack-compressed-block-width+ #x912B) 
(defconstant +pack-compressed-block-height+ #x912C) 
(defconstant +pack-compressed-block-depth+ #x912D) 
(defconstant +pack-compressed-block-size+ #x912E) 
(defconstant +unpack-compressed-block-width+ #x9127) 
(defconstant +unpack-compressed-block-height+ #x9128) 
(defconstant +unpack-compressed-block-depth+ #x9129) 
(defconstant +unpack-compressed-block-size+ #x912A) 
(defconstant +pack-compressed-block-width+ #x912B) 
(defconstant +pack-compressed-block-height+ #x912C) 
(defconstant +pack-compressed-block-depth+ #x912D) 
(defconstant +pack-compressed-block-size+ #x912E) 
