;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; sgix_line_quality_hint

(defconstant +line-quality-hint-sgix+ #x835B) 
