;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_occlusion_query2

(defconstant +any-samples-passed+ #x8C2F) 
(defconstant +any-samples-passed-ext+ #x8C2F) 
(defconstant +any-samples-passed+ #x8C2F) 
