;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; sgix_scalebias_hint

(defconstant +scalebias-hint-sgix+ #x8322) 
(defconstant +scalebias-hint-sgix+ #x8322) 
