;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; nv_deep_texture3d

(defconstant +max-deep-3d-texture-width-height-nv+ #x90D0) 
(defconstant +max-deep-3d-texture-depth-nv+ #x90D1) 
(defconstant +max-deep-3d-texture-width-height-nv+ #x90D0) 
(defconstant +max-deep-3d-texture-depth-nv+ #x90D1) 
