;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ext_framebuffer_multisample_blit_scaled

(defconstant +scaled-resolve-fastest-ext+ #x90BA) 
(defconstant +scaled-resolve-nicest-ext+ #x90BB) 
(defconstant +scaled-resolve-fastest-ext+ #x90BA) 
(defconstant +scaled-resolve-nicest-ext+ #x90BB) 
