;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; sgix_texture_coordinate_clamp

(defconstant +mirrored-repeat+ #x8370) 
