;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_color_buffer_float

(defconstant +rgba-float-mode-arb+ #x8820) 
(defconstant +rgba-float-mode-arb+ #x8820) 
(defconstant +clamp-vertex-color-arb+ #x891A) 
(defconstant +clamp-fragment-color-arb+ #x891B) 
(defconstant +clamp-read-color-arb+ #x891C) 
(defconstant +fixed-only-arb+ #x891D) 
(defglextfun "ClampColorARB" clamp-color-arb :return "void" :args
 ((:name |target| :type |ClampColorTargetARB| :direction :in)
  (:name |clamp| :type |ClampColorModeARB| :direction :in))
 :category "ARB_color_buffer_float" :deprecated nil :version "1.5") 
(make-extension-loader |ARB_color_buffer_float|
 (("ClampColorARB" clamp-color-arb :return "void" :args
   ((:name |target| :type |ClampColorTargetARB| :direction :in)
    (:name |clamp| :type |ClampColorModeARB| :direction :in))
   :category "ARB_color_buffer_float" :deprecated nil :version
   "1.5"))) 
