;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_shading_language_100

(defconstant +shading-language-version-arb+ #x8B8C) 
