;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_map_buffer_alignment

(defconstant +min-map-buffer-alignment+ #x90BC) 
(defconstant +path-stencil-depth-offset-factor-nv+ #x90BD) 
(defconstant +path-stencil-depth-offset-units-nv+ #x90BE) 
(defconstant +path-cover-depth-func-nv+ #x90BF) 
(defconstant +min-map-buffer-alignment+ #x90BC) 
