;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_internalformat_query

(defconstant +num-sample-counts+ #x9380) 
(defconstant +translated-shader-source-length-angle+ #x93A0) 
(defconstant +texture-usage-angle+ #x93A2) 
(defconstant +framebuffer-attachment-angle+ #x93A3) 
(defconstant +pack-reverse-row-order-angle+ #x93A4) 
(defconstant +program-binary-angle+ #x93A6) 
(defconstant +num-sample-counts+ #x9380) 
(defglextfun "GetInternalformativ" get-internalformat-iv :return "void" :args ((:name |target| :type |GLenum| :direction :in) (:name |internalformat| :type |GLenum| :direction :in) (:name |pname| :type |GLenum| :direction :in) (:name |bufSize| :type |SizeI| :direction :in) (:name |params| :type |Int32| :direction :out :array t :size bufsize)) :category "ARB_internalformat_query" :deprecated nil :version "4.2") 
(make-extension-loader |ARB_internalformat_query| (("GetInternalformativ" get-internalformat-iv :return "void" :args ((:name |target| :type |GLenum| :direction :in) (:name |internalformat| :type |GLenum| :direction :in) (:name |pname| :type |GLenum| :direction :in) (:name |bufSize| :type |SizeI| :direction :in) (:name |params| :type |Int32| :direction :out :array t :size bufsize)) :category "ARB_internalformat_query" :deprecated nil :version "4.2"))) 
