;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_framebuffer_srgb

(defconstant +framebuffer-srgb+ #x8DB9) 
