;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ibm_cull_vertex

(defconstant +cull-vertex-ibm+ #x1928A) 
(defconstant +cull-vertex-ibm+ #x1928A) 
