;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ati_pixel_format_float

(defconstant +rgba-float-mode-ati+ #x8820) 
(defconstant +color-clear-unclamped-value-ati+ #x8835) 
