;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; img_texture_compression_pvrtc2

(defconstant +compressed-rgba-pvrtc-2bppv2-img+ #x9137) 
(defconstant +compressed-rgba-pvrtc-4bppv2-img+ #x9138) 
(defconstant +max-debug-message-length+ #x9143) 
(defconstant +max-debug-logged-messages+ #x9144) 
(defconstant +debug-logged-messages+ #x9145) 
(defconstant +debug-severity-high+ #x9146) 
(defconstant +debug-severity-medium+ #x9147) 
(defconstant +debug-severity-low+ #x9148) 
(defconstant +max-debug-message-length-arb+ #x9143) 
(defconstant +max-debug-logged-messages-arb+ #x9144) 
(defconstant +debug-logged-messages-arb+ #x9145) 
(defconstant +debug-severity-high-arb+ #x9146) 
(defconstant +debug-severity-medium-arb+ #x9147) 
(defconstant +debug-severity-low-arb+ #x9148) 
