;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; oes_query_matrix

(defglextfun "QueryMatrixxOES" query-matrixx-oes :return "GLbitfield"
 :args
 ((:name |mantissa| :type |Fixed| :direction :out :array t :size
   #x10)
  (:name |exponent| :type |Int32| :direction :out :array t :size
   #x10))
 :category "OES_query_matrix" :deprecated nil :version "4.3") 
(make-extension-loader |OES_query_matrix|
 (("QueryMatrixxOES" query-matrixx-oes :return "GLbitfield" :args
   ((:name |mantissa| :type |Fixed| :direction :out :array t :size
     #x10)
    (:name |exponent| :type |Int32| :direction :out :array t :size
     #x10))
   :category "OES_query_matrix" :deprecated nil :version "4.3"))) 
