;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_transform_feedback_instanced

(defglextfun "DrawTransformFeedbackStreamInstanced" draw-transform-feedback-stream-instanced :return "void" :args ((:name |mode| :type |GLenum| :direction :in) (:name |id| :type |UInt32| :direction :in) (:name |stream| :type |UInt32| :direction :in) (:name |instancecount| :type |SizeI| :direction :in)) :category "ARB_transform_feedback_instanced" :deprecated nil :version "4.2") 
(defglextfun "DrawTransformFeedbackInstanced" draw-transform-feedback-instanced :return "void" :args ((:name |mode| :type |GLenum| :direction :in) (:name |id| :type |UInt32| :direction :in) (:name |instancecount| :type |SizeI| :direction :in)) :category "ARB_transform_feedback_instanced" :deprecated nil :version "4.2") 
(make-extension-loader |ARB_transform_feedback_instanced| (("DrawTransformFeedbackStreamInstanced" draw-transform-feedback-stream-instanced :return "void" :args ((:name |mode| :type |GLenum| :direction :in) (:name |id| :type |UInt32| :direction :in) (:name |stream| :type |UInt32| :direction :in) (:name |instancecount| :type |SizeI| :direction :in)) :category "ARB_transform_feedback_instanced" :deprecated nil :version "4.2") ("DrawTransformFeedbackInstanced" draw-transform-feedback-instanced :return "void" :args ((:name |mode| :type |GLenum| :direction :in) (:name |id| :type |UInt32| :direction :in) (:name |instancecount| :type |SizeI| :direction :in)) :category "ARB_transform_feedback_instanced" :deprecated nil :version "4.2"))) 
