;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_explicit_uniform_location

(defconstant +max-uniform-locations+ #x826E) 
(defconstant +max-uniform-locations+ #x826E) 
