;;;; This file was automatically generated by /home/james/src/lisp/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_stencil_texturing

(defconstant +depth-stencil-texture-mode+ #x90EA) 
(defconstant +depth-stencil-texture-mode+ #x90EA) 
